package com.tutorialspoint.TutorialPoint.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {
    @GetMapping(value = "/")
    public String hello(){
        return "Hello Motherfuckers! :)";
    }
}

/*
Springboot Code Structure

my-springboot-project/
├── .gitignore                   # Git ignore file
├── mvnw                         # Wrapper for Maven (Unix)
├── mvnw.cmd                     # Wrapper for Maven (Windows)
├── pom.xml                      # Maven Project Object Model (POM) file (for Maven projects)
├── build.gradle                 # Gradle build script (for Gradle projects)
├── src/
│   ├── main/
│   │   ├── java/
│   │   │   └── com/
│   │   │       └── example/
│   │   │           └── myapp/
│   │   │               ├── MySpringBootApplication.java   # Main Spring Boot Application class
│   │   │               ├── controller/
│   │   │               │   └── MyController.java         # Controller classes
│   │   │               ├── service/
│   │   │               │   └── MyService.java           # Service classes
│   │   │               ├── repository/
│   │   │               │   └── MyRepository.java        # Repository classes (if using JPA)
│   │   │               └── model/
│   │   │                   └── MyModel.java             # Model classes
│   │   ├── resources/
│   │   │   ├── application.properties   # Main application properties
│   │   │   ├── application.yml         # Optional alternative to properties (for YAML config)
│   │   │   ├── static/                 # Static resources (images, CSS, JS, etc.)
│   │   │   └── templates/              # Thymeleaf templates (if using)
│   │   └── webapp/
│   │       └── WEB-INF/                # Web application configuration (for traditional WAR)
│   ├── test/
│   │   └── java/
│   │       └── com/
│   │           └── example/
│   │               └── myapp/
│   │                   ├── MySpringBootApplicationTests.java  # Test classes for the application
│   │                   └── controller/
│   │                       └── MyControllerTests.java        # Test classes for controllers
└── target/                        # Compiled and packaged artifacts (generated by Maven/Gradle)

 */